language: node_js
node_js:
- '12'
dist: eoan
sudo: required
branches:
  only:
  - feature/travis-ci
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in id_rsa-encrypted -out id_rsa -d
before_script:
- npm install -g @angular/cli
script:
- ng lint
- npm run test-headless
- ng build --prod
deploy:
  edge: true
  provider: pages:git
  repo: git@github.com:AgileMetrics/AgileMetrics.github.io.git
  deploy_key: id_rsa
  target_branch: gh-pages
  local_dir: dist/agile-metrics-frontend
